# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 773687f29e95b702cec94e7b772a1cc1bbe11466aae3271fb637c0b7cd19660b878a515b69c7f979cb5f178236fc3d8a5fe2e72703c996adb01f81f4d287fd70

test:
  secret_key_base: aadfbef6840e95f6a603c288ea098b2d15ce11522c6f44b0e632cfc5c53a002903253ab339e52a546e7c96eaba362a6caed1ad70e61822d6a4f0bf1fa189380b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
